### PR TITLE
switch to https

### PR DESCRIPTION
**Pull request by jjmakin**
Use https rather than http for calls so the code can be put on https pages without setting off all the security alarms in a browser

### CODE REVIEW

**Comment by jjmakin** [comment]
I've found this project extremely useful over the last few years, and as such I'd like to give something back to the project.

**Comment by HeavyThumper** [comment]
Instead - just delete the "http:" altogether.  There's no requirement - and now it's compatible whether your host application is using http or https.

**Comment by jjmakin** [comment]
Wow, I totally didn't know that. Thank you. Are you just a passer buy or one of the authors?
I suppose I should close this and make a new request.

**Comment by HeavyThumper** [comment]
Just a "drive-by".  I just started using this and that was an item that was breaking for me as I'm accessing my site via https.

Additionally, I've deleted the "sensor" parameter from a few references - per Google's docs this parameter is deprecated.  So now I've eliminated most of the warning messages.

**Pull request closed without merging**
